### ISSUE TITLE
black activity with a 'Helloooo' toast when returning from a locked app

### ISSUE THREAD

**Issue by uniqdom** [twinone/AppLocker#10]
Hi, I'm using the version that is in F-droid repository. 

When you return using the back button from an app that is locked, I see a black activity with a toast that says 'Helloooo'. This can also be seen when you press home button and then you try to open again the same or another locked app. This behavior doesn't happen when you go back from your AppLocker app.

I have done a video to show the behavior: https://www.youtube.com/watch?v=iq0tTd48L_Q

Regards

**Comment by twinone** [comment]
That should only happen in Google Play, as it's the activity launching the interstitial ads. I'll take a look at it.

**Comment by twinone** [comment]
I've just pushed a commit, I assume it's fixed. Please let me know if it's not.

**Comment by adithyavr** [comment]
Hi I am still getting this toast issue on very 2.5.1 . I installed it from F-Droid. If there is an update to this can you pish on on that repository too?

**Comment by twinone** [comment]
Please check you have the version v2.5.1-20150604 and not just v2.5.1.
I'll create a new release with v2.5.2 to avoid confusion. Please let me know if it's still there.

**Comment by glepretre** [comment]
@twinone F-droid latest version still is 2.5.1 from March 16 for info :wink:

**Comment by adithyavr** [comment]
@twinone  The F-Droid version is still 2.5.1

**Comment by twinone** [comment]
Since 2 days ago the new version is available on F-Droid.
